server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: 192.168.56.128
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route_payment1
          # 负载均衡写法lb://服务注册中心的服务名称
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/consul/payment # 断言，路径相匹配的进行路由，具体路径