server:
  port: 80
spring:
  application:
    name: alibaba-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
#应该是为controller，提供@value注解使用
service-url:
  nacos-user-service: http://alibaba-nacos-payment