server:
  port: 80
spring:
  application:
    name: cloud-consumer-consul-order
  cloud:
    consul:
      # consul注册中心地址
#      host: 192.168.0.44
      host: 192.168.56.128
      port: 8500
      discovery:
#        hostname: 192.168.0.233
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true