server:
  # consul服务端口
  port: 8006
spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.0.44
      port: 8500
      discovery:
        hostname: 192.168.0.233
        service-name: ${spring.application.name}
        #添加心跳检查
        heartbeat:
          enabled: true