server:
  port: 8802

#spring:
#  application:
#    name: cloud-stream-producer
#  cloud:
#    stream:
#      binders: # 在此处配置要绑定的rabbitmq的服务信息；
#        defaultRabbit: # 表示定义的名称，用于于binding整合
#          type: rabbit # 消息组件类型
#          environment: # 设置rabbitmq的相关的环境配置
#            spring:
#              rabbitmq:
#                host: 192.168.56.128
#                port: 5672
#                username: root
#                password: 123456
#      bindings: # 服务的整合处理
#        output: # 这个名字是一个通道的名称
#          destination: studyExchange # 表示要使用的Exchange名称定义
#          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
#          binder: defaultRabbit  # 设置要绑定的消息服务的具体设置

spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 192.168.56.128
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          #定义分组，相同的组不会导致消息重复消费，不同组会消息重复消费
          group: consumer_a

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: ${spring.application.name}1
    prefer-ip-address: true


